# Generated by Django 4.2.27 on 2026-02-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('english', models.TextField(db_index=True)),
                ('persian', models.TextField()),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='team1.category')),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='SurvivalGame',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('survival_game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('lives', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survival_game',
                'indexes': [models.Index(fields=['user_id'], name='survival_ga_user_id_88b28a_idx'), models.Index(fields=['user_id', 'date'], name='survival_ga_user_id_8e9e8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('correct_count', models.IntegerField(blank=True, null=True)),
                ('question_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quiz',
                'indexes': [models.Index(fields=['user_id'], name='quiz_user_id_f8bcad_idx'), models.Index(fields=['user_id', 'date'], name='quiz_user_id_9aa7f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_word_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_words/')),
                ('last_check_date', models.DateField(blank=True, null=True)),
                ('leitner_type', models.CharField(choices=[('new', 'New'), ('1day', '1 Day'), ('3days', '3 Days'), ('7days', '7 Days'), ('mastered', 'Mastered')], default='new', max_length=10)),
                ('user_id', models.UUIDField(db_index=True)),
                ('word', models.ForeignKey(db_column='word_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='team1.word')),
            ],
            options={
                'db_table': 'user_words',
                'indexes': [models.Index(fields=['word'], name='user_words_word_id_ce7381_idx'), models.Index(fields=['user_id'], name='user_words_user_id_27aaa5_idx')],
            },
        ),
    ]
